# Generated by Django 5.0.3 on 2024-05-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcareworker",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
