# Generated by Django 5.0.3 on 2024-06-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mother", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mother_visit",
            name="date_of_next_visit",
            field=models.DateField(),
        ),
    ]
