# Generated by Django 5.0.3 on 2024-04-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="healthcareworker",
            old_name="user_name",
            new_name="username",
        ),
    ]
